# Generated by Django 6.0.1 on 2026-01-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tiempo_llegada', models.PositiveIntegerField()),
                ('rafaga_cpu', models.PositiveIntegerField()),
                ('duracion_es', models.PositiveIntegerField()),
            ],
        ),
    ]
