# Generated by Django 6.0.1 on 2026-01-09 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0002_proceso_inicio_es_alter_proceso_duracion_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='nombre',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
