# Generated by Django 6.0.1 on 2026-01-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0004_sequence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sequence',
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
    ]
