# Generated by Django 6.0.1 on 2026-01-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0005_delete_sequence_alter_proceso_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='duracion_es',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='inicio_es',
        ),
        migrations.AddField(
            model_name='proceso',
            name='es',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proceso',
            name='rafaga_cpu',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tiempo_llegada',
            field=models.IntegerField(),
        ),
    ]
