# Generated by Django 6.0.1 on 2026-01-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0006_remove_proceso_duracion_es_remove_proceso_inicio_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='es',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
